version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./docker/dynamodb/data:/data
    ports:
      - 8000:8000
