import { APIGatewayEvent } from 'aws-lambda';
type Method = 'POST';

export const generateAPIGatewayEvent = (
  method: Method,
  path: string
): APIGatewayEvent => {
  return {
    resource: path,
    path: path,
    httpMethod: method,
    headers: {
      'Content-Length': '0',
      Host: 'xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com',
      'User-Agent': 'PostmanRuntime/7.28.1',
      'X-Amzn-Trace-Id': 'Root=1-60e5c940-42a052bd17c8de413ff48ee0',
      'X-Forwarded-For': '123.123.123.123',
      'X-Forwarded-Port': '443',
      'X-Forwarded-Proto': 'https',
      accept: '*/*',
      'accept-encoding': 'gzip, deflate, br',
    },
    multiValueHeaders: {
      'Content-Length': ['0'],
      Host: ['xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com'],
      'Postman-Token': ['0bf0865f-daa7-48e0-9090-d0da351d9296'],
      'User-Agent': ['PostmanRuntime/7.28.1'],
      'X-Amzn-Trace-Id': ['Root=1-60e5c940-42a052bd17c8de413ff48ee0'],
      'X-Forwarded-For': ['123.123.123.123'],
      'X-Forwarded-Port': ['443'],
      'X-Forwarded-Proto': ['https'],
      accept: ['*/*'],
      'accept-encoding': ['gzip, deflate, br'],
    },
    queryStringParameters: null,
    multiValueQueryStringParameters: null,
    requestContext: {
      accountId: '000000000000',
      apiId: 'xxxxxxxxxx',
      domainName: 'xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com',
      domainPrefix: 'xxxxxxxxxx',
      extendedRequestId: 'CGxiLgg0tjMEMeQ=',
      httpMethod: 'GET',
      authorizer: null,
      identity: {
        clientCert: null,
        accessKey: null,
        accountId: null,
        caller: null,
        apiKey: null,
        apiKeyId: null,
        cognitoAuthenticationProvider: null,
        cognitoAuthenticationType: null,
        cognitoIdentityId: null,
        cognitoIdentityPoolId: null,
        principalOrgId: null,
        sourceIp: '123.123.123.123',
        user: null,
        userAgent: 'PostmanRuntime/7.28.1',
        userArn: null,
      },
      path: path,
      protocol: 'HTTP/1.1',
      requestId: 'CGxiLgg0tjMEMeQ=',
      requestTime: '07/Jul/2021:15:33:20 +0000',
      requestTimeEpoch: 1644296458000,
      resourceId: `${method} ${path}`,
      resourcePath: path,
      stage: '$default',
    },
    pathParameters: null,
    stageVariables: null,
    body: null,
    isBase64Encoded: false,
  };
};
